version: "3.7"

services:
  deno:
    build:
      context: ./deno
    ports:
      - 5000:5000
      - 9229:9229
    working_dir: /app
    volumes:
      - ./src/:/app
    command: denon run --allow-net --allow-write --allow-read --allow-env --allow-plugin --unstable  server.ts

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: deno_survey
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
